/**
 * Single source of truth for everything that describes the site to the outside
 * world: search engines, AI answer engines, social crawlers and JSON-LD.
 *
 * Every metadata export and every structured-data block reads from here, so a
 * change to the phone number or the address propagates everywhere at once
 * instead of drifting between the footer, the schema and the OG tags. Entity
 * consistency (same name, same NAP, same identifiers everywhere) is the single
 * biggest lever for how confidently Google and LLM-based search surface a
 * small brand.
 */

/**
 * Canonical origin, no trailing slash.
 *
 * Order of precedence:
 *  1. NEXT_PUBLIC_SITE_URL – set this in Vercel for full control.
 *  2. VERCEL_PROJECT_PRODUCTION_URL – the production domain Vercel knows about,
 *     so preview deploys still emit production canonicals instead of pointing
 *     search engines at a preview URL.
 *  3. The live domain, hard-coded as a last resort.
 */
export const SITE_URL = (
  process.env.NEXT_PUBLIC_SITE_URL ||
  (process.env.VERCEL_PROJECT_PRODUCTION_URL
    ? `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`
    : 'https://northwestcoast.no')
).replace(/\/$/, '');

/** Absolute URL for a site-relative path. Structured data must never use relative URLs. */
export const abs = (path = '/') => `${SITE_URL}${path.startsWith('/') ? path : `/${path}`}`;

export const SITE = {
  /** Legal entity name – must match Brønnøysund and the footer verbatim. */
  legalName: 'Northwestcoast AS',
  /** Brand name used in titles and by answer engines. */
  name: 'NorthWest Coast',
  /** Norwegian organisation number, doubles as the schema.org identifier. */
  orgNumber: '998 196 159',
  /** Flagship product – the entity we actually want to rank for. */
  product: 'Argostep',
  tagline: 'Maritime leidere for norske fartøy',
  description:
    'NorthWest Coast produserer Argostep – en lett, modulær maritim leider i glassfiberarmert plast. ISO 799-1:2019-sertifisert og godkjent av Sjøfartsdirektoratet. Norsk produksjon fra Sunnmøre.',
  locale: 'nb_NO',
  lang: 'nb',
  phone: '+4790407341',
  phoneDisplay: '+47 904 07 341',
  email: 'arve@astep.no',
  address: {
    poBox: 'Postboks 79',
    postalCode: '6281',
    city: 'Søvik',
    region: 'Møre og Romsdal',
    country: 'NO',
  },
  /**
   * Approximate coordinates for Søvik, Haram (Møre og Romsdal). Geo data helps
   * local packs and gives answer engines a place to anchor the business to.
   */
  geo: { lat: 62.5747, lng: 6.2839 },
  sameAs: [
    'https://www.facebook.com/',
    'https://www.instagram.com/',
    'https://www.linkedin.com/',
  ],
  founders: ['Kristian B. Dyb', 'Arve Toven', 'Tor Arne Reitan'],
  /** Default social/answer-engine preview image (generated by app/opengraph-image.tsx). */
  ogImage: '/opengraph-image',
} as const;

/**
 * Site-wide page registry. Used to build the sitemap, the llms.txt manifest and
 * breadcrumb trails, so a new page only ever has to be declared in one place.
 */
export type PageEntry = {
  path: string;
  title: string;
  /** One-line summary written to be quotable verbatim by an answer engine. */
  summary: string;
  /** Sitemap hints. */
  priority: number;
  changeFrequency: 'daily' | 'weekly' | 'monthly' | 'yearly';
};

export const PAGES: PageEntry[] = [
  {
    path: '/',
    title: 'Argostep maritim leider – NorthWest Coast',
    summary:
      'Forsiden: hva Argostep er, sertifiseringer, 3D-modell av leideren og kontaktinformasjon.',
    priority: 1,
    changeFrequency: 'monthly',
  },
  {
    path: '/produkt',
    title: 'Argostep Livbåtleider – produkt og spesifikasjoner',
    summary:
      'Tekniske spesifikasjoner: lengder 2–15 m, glassfiberarmert plast, ISO 799-1:2019, modulært klikk-koblet system med utskiftbare enkelttrinn.',
    priority: 0.9,
    changeFrequency: 'monthly',
  },
  {
    path: '/leiderkalkulator',
    title: 'Leiderkalkulator – regn ut riktig leiderlengde',
    summary:
      'Gratis verktøy som regner ut hvor lang maritim leider et fartøy trenger ut fra fribord, innstigningshøyde og lastkondisjon, og foreslår riktig Argostep-modell med antall trinn.',
    priority: 0.9,
    changeFrequency: 'monthly',
  },
  {
    path: '/bestill',
    title: 'Bestill Argostep Livbåtleider',
    summary:
      'Konfigurator med 3D-visning: velg lengde 3–15 m, antall og oppbevaringsskap, og se veiledende pris.',
    priority: 0.8,
    changeFrequency: 'monthly',
  },
  {
    path: '/galleri',
    title: 'Bildegalleri – Argostep i bruk',
    summary: 'Bilder av leideren, oppbevaringsskap og referansefartøy langs norskekysten.',
    priority: 0.6,
    changeFrequency: 'monthly',
  },
  {
    path: '/vedlikehold',
    title: 'Vedlikehold av maritim leider',
    summary:
      'Slik vedlikeholdes Argostep-leideren, og skjema for å registrere utført vedlikehold for eget fartøy.',
    priority: 0.7,
    changeFrequency: 'monthly',
  },
  {
    path: '/faq',
    title: 'Ofte stilte spørsmål om Argostep',
    summary:
      'Svar på spørsmål om godkjenning, lengder, materialvalg, montering, levetid, reservedeler og leveringstid.',
    priority: 0.8,
    changeFrequency: 'monthly',
  },
  {
    path: '/nyheter',
    title: 'Nyheter fra NorthWest Coast',
    summary: 'Nyheter, produktoppdateringer og caser fra maritime leidere.',
    priority: 0.6,
    changeFrequency: 'weekly',
  },
];

/**
 * Builds an openGraph metadata block for a child page.
 *
 * Next.js does NOT deep-merge `openGraph` from the root layout: a page that
 * declares its own og:title silently drops the inherited og:image, and the page
 * ends up sharing as a blank card. This helper re-attaches the default image (and
 * the site-level constants) so each page only has to supply what is actually
 * page-specific.
 */
export function pageOpenGraph({
  path,
  title,
  description,
  type = 'website',
  images,
}: {
  path: string;
  title: string;
  description: string;
  type?: 'website' | 'article';
  images?: { url: string; alt?: string }[];
}) {
  return {
    type,
    url: path,
    siteName: SITE.name,
    locale: SITE.locale,
    title,
    description,
    images: images ?? [
      { url: SITE.ogImage, width: 1200, height: 630, alt: 'Argostep maritim leider' },
    ],
  } as const;
}
